### ISSUE TITLE
Provide examples of songs using the keyboards notation

### ISSUE THREAD

**Issue by pengux** [billgathen/pentaphone#2]
Maybe you could provide examples of songs that can be played with the pentaphone with keyboard notations, such as:

```
w-j-k-l d-space-l
```

Would be cool

**Comment by billgathen** [comment]
I use it entirely for improvisation, so it never even occurred to me to look up actual songs to play with it! :laughing:  

I think any modern pop/rock songs that did fit would be a copyright violation, but this page lists a bunch of public domain songs that are pentatonic: http://www.bethsnotesplus.com/2012/02/pentatonic-songs.html

Most of them I don't know, but I recognize a few.

S = space
- Farmer in the Dell: S-SS-SS-...jk-kk-kk-...l-l-;lkjSkkjjS-
- Swing Low, Sweet Chariot: kS--kS-S;l-kkkkkkl-;- (this sounds a bit wonky because of the high 6, 5 in the middle)
- Camptown Races: llkl;lk-kS---kS---

It's not a terribly-pretty format, but it might be helpful. Thanks for the suggestion!

**Comment by billgathen** [comment]
Done! Check it out. Pressing `x` toggles the song examples.

http://billgathen.github.io/pentaphone/dist/index.html

Thanks again for the suggestion. :smile:
